package com.example.lettuceapp

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import com.lettuceapp.data.DatabaseHandler

class MainPage : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { // do this stuff when page loads
        DatabaseHandler(this) // call to dB, not sure if need here cuz not looking at db

        // autogenerated. think it sets this kt to respective xml
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main_page)

        // assign buttons & button onclick
        val createBtn = findViewById<Button>(R.id.createProfile)  // create profile btn
        createBtn.setOnClickListener{
            val intent = Intent(this, CreateProfileChoice::class.java) // destination kt file
            startActivity(intent)
        }

        val loginBtn = findViewById<Button>(R.id.login) // Login Btn
        loginBtn.setOnClickListener{
            val intent = Intent(this, Login::class.java)
            startActivity(intent)
        }

        val guestBtn = findViewById<Button>(R.id.guest) // Guest Btn
        guestBtn.setOnClickListener{
            val intent = Intent(this, SelectionPage::class.java)
            startActivity(intent)
        }

        val dbBtn = findViewById<Button>(R.id.displayDB) // displayDB Btn
        dbBtn.setOnClickListener{
            val intent = Intent(this, DisplayDBData::class.java)
            startActivity(intent)
        }
    }
}
